/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.File;
import javax.swing.JFileChooser;
import model.Dokumen;

/**
 *
 * @author user only
 */
public class MyNotepad extends javax.swing.JFrame {

    private Dokumen dokumen;

    /**
     * Creates new form MyNotepad
     */
    public MyNotepad() {
        initComponents();
        dokumen = new Dokumen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        isiDokumenArea = new javax.swing.JTextArea();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        bacaMenuItem = new javax.swing.JMenuItem();
        simpanMenuItem = new javax.swing.JMenuItem();
        keluarMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My Simple Notepad");

        isiDokumenArea.setColumns(20);
        isiDokumenArea.setRows(5);
        jScrollPane1.setViewportView(isiDokumenArea);

        fileMenu.setText("File");

        bacaMenuItem.setText("Baca");
        bacaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bacaMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(bacaMenuItem);

        simpanMenuItem.setText("Simpan");
        simpanMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(simpanMenuItem);

        keluarMenuItem.setText("Keluar");
        keluarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(keluarMenuItem);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keluarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarMenuItemActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_keluarMenuItemActionPerformed

    private void bacaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bacaMenuItemActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            dokumen.bacaDariFile(fc.getSelectedFile());
            isiDokumenArea.setText(dokumen.getIsi());
        }
    }//GEN-LAST:event_bacaMenuItemActionPerformed

    private void simpanMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanMenuItemActionPerformed
        JFileChooser jfc = new JFileChooser();
        int returnVal = jfc.showSaveDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            dokumen.setIsi(isiDokumenArea.getText());
            dokumen.simpanKeFile(jfc.getSelectedFile());

        }
    }//GEN-LAST:event_simpanMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyNotepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyNotepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyNotepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyNotepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyNotepad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem bacaMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JTextArea isiDokumenArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem keluarMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem simpanMenuItem;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the dokumen
     */
    public Dokumen getDokumen() {
        return dokumen;
    }

    /**
     * @param dokumen the dokumen to set
     */
    public void setDokumen(Dokumen dokumen) {
        this.dokumen = dokumen;
    }
}
